package bioLabUI;

import interfaces.PatientManager;

import java.util.List;
import java.util.Scanner;

import bioLabPOJOS.Patient;

/**
 * Provides a text-based interface for managing patient records.
 * Supports standard CRUD operations and multimedia (image) associations.
 * this class does not know how to save data; it only collects the text from the keyboard and 
 * hands it over to the PatientManager (the database worker).
 */

public class PatientUI {

    private PatientManager patientManager;
    private Scanner scanner;

    /**
     * Constructor injecting the PatientManager implementation.
     * 
     * @param patientManager The logic handler for patient data operations.
     * This means your UI is loosely coupled and doesn't care if the database is SQLite, MySQL, or a text file.
     */
    
    public PatientUI(PatientManager patientManager) {
        this.patientManager = patientManager;
        this.scanner = new Scanner(System.in);
    }

    /**
     * Displays the main patient management menu.
     */
    
    public void showMenu() {
        int option;

        do {
            System.out.println("\n=== PATIENT MENU ===");
            System.out.println("1. Add patient");
            System.out.println("2. Show all patients");
            System.out.println("3. Find patient by ID");
            System.out.println("4. Update patient");
            System.out.println("5. Delete patient");
            System.out.println("6. Add patient image");
            System.out.println("0. Exit");
            System.out.print("Choose an option: ");

            option = Integer.parseInt(scanner.nextLine());

            switch (option) {
                case 1 -> addPatient();
                case 2 -> showAllPatients();
                case 3 -> findPatientById();
                case 4 -> updatePatient();
                case 5 -> deletePatient();
                case 6 -> addPatientImage();
            }

        } while (option != 0);
    }

    /**
     * Collects demographic information to register a new patient.
     */
    
    private void addPatient() {
        System.out.print("First name: ");
        String firstName = scanner.nextLine();

        System.out.print("Last name: ");
        String lastName = scanner.nextLine();

        System.out.print("Date of birth: ");
        String dob = scanner.nextLine();

        System.out.print("Gender: ");
        String gender = scanner.nextLine();

        System.out.print("Phone: ");
        String phone = scanner.nextLine();

        System.out.print("Address: ");
        String address = scanner.nextLine();

     // ID is set to 0 as it is usually auto-generated by the database
     //You pass a 0 into the POJO. When the PatientManager receives this object and sends it to SQLite,
     //SQLite ignores the 0 and generates the next real number (e.g., 105) automatically using AUTOINCREMENT.
        
        Patient patient = new Patient(0, firstName, lastName, dob, gender, phone, address);
        patientManager.addPatient(patient);
    }

    /**
     * Lists all registered patients in the database.
     */
    
    private void showAllPatients() {
        List<Patient> patients = patientManager.getAllPatients();

        for (Patient p : patients) {
            System.out.println("ID: " + p.getPatientId());
            System.out.println("Name: " + p.getFirstName() + " " + p.getLastName());
            System.out.println("--------------------------");
        }
    }

    /**
     * Retrieves specific patient details by their ID.
     */
    
    private void findPatientById() {
        System.out.print("ID: ");
        int id = Integer.parseInt(scanner.nextLine());

        Patient p = patientManager.getPatientById(id);

        if (p != null) {
            System.out.println("Name: " + p.getFirstName());
        } else {
            System.out.println("Not found");
        }
    }

    /**
     * Updates demographic information for an existing patient.
     */
    
    private void updatePatient() {
        /**
         * Updates demographic information for an existing patient.
         */
            System.out.print("Enter ID of the patient to update: ");
            int id = Integer.parseInt(scanner.nextLine());

            System.out.print("New First name: ");
            String firstName = scanner.nextLine();

            System.out.print("New Last name: ");
            String lastName = scanner.nextLine();

            System.out.print("New Date of birth (yyyy-mm-dd): ");
            String dob = scanner.nextLine();

            System.out.print("New Gender: ");
            String gender = scanner.nextLine();

            System.out.print("New Phone: ");
            String phone = scanner.nextLine();

            System.out.print("New Address: ");
            String address = scanner.nextLine();

            Patient p = new Patient(id, firstName, lastName, dob, gender, phone, address);
            patientManager.updatePatient(p);
            
            System.out.println("Patient updated request sent.");
        }

    /**
     * Removes a patient from the system.
     */
    
    private void deletePatient() {
        System.out.print("ID: ");
        int id = Integer.parseInt(scanner.nextLine());
        patientManager.deletePatient(id);
    }
    
    /**
     * Handles the association of a physical image file with a patient record.
     * This triggers the JDBC BLOB handling logic.
     */
    
    private void addPatientImage() {
        System.out.print("Patient ID: ");
        int id = Integer.parseInt(scanner.nextLine());

        System.out.print("Image path: ");
        String imagePath = scanner.nextLine();

        patientManager.updatePatientImage(id, imagePath);
    }
}